# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choiceText',
            field=models.CharField(max_length=200, verbose_name='choiceText'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='votes'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pubDate',
            field=models.DateTimeField(verbose_name='datePublished'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionText',
            field=models.CharField(max_length=200, verbose_name='questionText'),
        ),
    ]
